replicas: 2

image:
  tag: latest
  pullPolicy: Always

resources:
  limits:
    cpu: 4
    memory: 8Gi
  requests:
    cpu: 0.5
    memory: 500Mi
  disk: "50Gi"
  storageclass: "default"

cleanRun: false

volumeMounts:
- name: docker-socket
  mountPath: /var/run/docker.sock
  readOnly: false

volumes:
- name: docker-socket
  hostPath:
    path: /var/run/docker.sock

extraEnv: {}

extraContainers: []
